version: '3.8'

services:
  backend:
    build:
      context: ./Backend-Example
      dockerfile: Dockerfile
    container_name: ai-tool-backend
    ports:
      - "3001:3001"
    
    
    restart: unless-stopped
    networks:
      - ai-tool-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ai-tool-frontend
    ports:
      - "5173:5173"
    networks:
      - ai-tool-network

networks:
  ai-tool-network:
    driver: bridge


