version: '3.8'

services:
  backend:
    build:
      context: ./Backend-Example
      dockerfile: Dockerfile
    container_name: ai-tool-backend
    ports:
      - "3001:3000"
    env_file:
      - ./Backend-Example/.env
    restart: unless-stopped
    networks:
      - ai-tool-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: ai-tool-frontend
    ports:
      - "5174:5173"
    networks:
      - ai-tool-network

networks:
  ai-tool-network:
    driver: bridge
